# Generated by Django 4.2.6 on 2023-10-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile/profile_pics/default.png', upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x0000024FB4939BD0>/profile/profile_pics/%Y/%m/%d/'),
        ),
    ]
