# Generated by Django 4.2.6 on 2023-10-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='post/photos/default.png', upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x000002012B939710>/post/photos/%Y/%m/%d/'),
        ),
    ]
