# Generated by Django 4.2.6 on 2023-10-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='post/photos/default.png', upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x0000021BCAEF9CD0>/post/photos/%Y/%m/%d/'),
        ),
    ]
