# Generated by Django 4.2.6 on 2023-10-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='post/photos/default.png', upload_to='<django.db.models.fields.related.ForeignKey>/post/photos/%Y/%m/%d/'),
        ),
    ]
